Refresh s3 credentials.  Addresses #55.
DataBiosphere/cgp-dss-data-loader pull request #59
Opened 2018-11-19 23:53 UTC by DailyDreaming

Addresses #55.

This attempts to refresh the s3 client when credentials expire.  Not sure if we can test this with travis since travis tests expire at 10 minutes and credentials require a minimum value of 900 seconds (15 minutes) that they are valid for.

2018-11-21 18:20 UTC, mikebaumann commented on loader/base_loader.py
> +        :return: Returns an empty dict or a head response containing a dictionary of metadata values.
I would put the typical expected case first, followed by what is returned in the case of an error. Something like:
```
Returns a head response containing a dictionary of metadata values, or an empty dict in the case of an error.
```

2018-11-21 18:22 UTC, mikebaumann requested changes
This looks good to me, Lon. Thanks!
Just one small nit regarding a comment.

2018-11-22 01:41 UTC, DailyDreaming commented
Thanks @mikebaumann !  We'll talk on Monday, have a good Thanksgiving!

2018-11-26 18:11 UTC, jessebrennan approved these changes
This is nice! It is theoretically possible to test this on travis, but as you pointed out it will take ~15 min. Travis only times out if nothing is printed on the screen. As long as some manual testing has been done, that's fine with me.

Maybe we could add a test, but then just disable it by default for travis?

2018-11-28 17:19 UTC, mikebaumann approved these changes
Thanks, Lon!
Please go ahead and merge this.

2018-11-30 00:34 UTC, merged